print("What do you get when you cross a snowman with a vampire?")
input()
print("Frostbite!")
print()
print("What do dentists call am astronaut\'s cavity?")
input()
print("A black hole")
print()
print("Knock Knock.")
input()
print("Interrupting cow!")
input()
print("Interrupting cow wh")
print("-MOO!")